export const CHANGE_BACKGROUND = "CHANGE_BACKGROUND";
export const DELETE_IMG = "DELETE_IMG";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EXIT_DETAIL = "EXIT_DETAIL";
export const UPDATE_OPENDETAIL = "UPDATE_OPENDETAIL";
